### ISSUE TITLE
Implement Software Development Lifecycle

### ISSUE THREAD

**Issue by znatty22** [NIH-NCPI/ncpi-fhir-ig-2#10]
- [x] Create the standard set of git repo labels for all branch types: feature, refactor, devops, bug, documentation, test
- [x] Create a git repo pull request template that automatically populates PR descriptions when the PR is opened
- [x] Create a README with a contributors guide OR create a separate CONTRIBUTING.md for the repo so that developers understand what the software development lifecycle is
- [x] Add Github release workflow so that IGs can be versioned and archived via releases
- [x] Setup deploy previews for the IG website so that every PR has a preview of the IG with the changes introduced in the PR
- [x] (Maybe) Setup IG validation that runs on every pushed commit
